{{ config(post_hook="truncate table {{source('DEVELOPER_DB','INCREMENTAL_US_ACCIDENT_STAGE_TABLE')}}",
materialized='incremental') }}
select c.DATE_ID,D.ADD_ID,e.DRON_ID,r.REASON_ID,m.SEVERITY,m.TEMPERATURE_F_,m.WIND_CHILL_F_,m.HUMIDITY_,
m.PRESSURE_IN_,m.VISIBILITY_MI_,m.WIND_DIRECTION,m.WIND_SPEED_MPH_,m.PRECIPITATION_IN_,m.WEATHER_CONDITION,
count(m.ID) as No_of_accidents from "DEVELOPER_DB"."TIRUPATHIRAO_SCHEMA"."INCREMENTAL_ACCIDENT_CONVERT_DATE" as m

left outer join "DEVELOPER_DB"."TIRUPATHIRAO_SCHEMA"."CALENDER_DIMENTIONS_TABLE" as c on m.DATE_ID=c.DATE_ID

left outer join "DEVELOPER_DB"."TIRUPATHIRAO_SCHEMA"."INCREMENTAL_ADDRESS_DIM" as D on m.CITY=D.CITY and m.COUNTRY=D.COUNTRY and
m.STATE=D.STATE and m.ZIPCODE=D.ZIPCODE and m.COUNTY=D.COUNTY and m.TIMEZONE=D.TIMEZONE and m.AIRPORT_CODE=D.AIRPORT_CODE and
m.STREET=D.STREET

left outer join "DEVELOPER_DB"."TIRUPATHIRAO_SCHEMA"."INCREMENTAL_DRON_DIM" as e on
m.SUNRISE_SUNSET=e.SUNRISE_SUNSET and
m.CIVIL_TWILIGHT=e.CIVIL_TWILIGHT and m.NAUTICAL_TWILIGHT=e.NAUTICAL_TWILIGHT and m.ASTRONOMICAL_TWILIGHT=e.ASTRONOMICAL_TWILIGHT

left outer join  "DEVELOPER_DB"."TIRUPATHIRAO_SCHEMA"."INCREMENTAL_REASON_DIM" as r on
m.AMENITY=r.AMENITY and m.BUMP=r.BUMP and m.CROSSING=r.CROSSING and
m.GIVE_WAY=r.GIVE_WAY and m.JUNCTION=r.JUNCTION and m.NO_EXIT=r.NO_EXIT and m.RAILWAY=r.RAILWAY and m.ROUNDABOUT=r.ROUNDABOUT and m.STATION=r.STATION and
m.STOP=r.STOP and m.TRAFFIC_CALMING=r.TRAFFIC_CALMING and m.TRAFFIC_SIGNAL=r.TRAFFIC_SIGNAL and m.TURNING_LOOP=r.TURNING_LOOP

where m._MODIFIED=D.dimention_Load_time and m._MODIFIED=e.dimention_Load_time and m._MODIFIED=r.dimention_Load_time

group by c.DATE_ID,D.ADD_ID,e.DRON_ID,r.REASON_ID,m.SEVERITY,m.TEMPERATURE_F_,m.WIND_CHILL_F_,m.HUMIDITY_,
m.PRESSURE_IN_,m.VISIBILITY_MI_,m.WIND_DIRECTION,m.WIND_SPEED_MPH_,m.PRECIPITATION_IN_,m.WEATHER_CONDITION,m.ID
