select D.ADD_ID,count(D.ADD_ID) as no_of_accident  from "DEVELOPER_DB"."TIRUPATHIRAO_SCHEMA"."US_ACCIDENT_STAGE_TABLE" as f
left join  "DEVELOPER_DB"."TIRUPATHIRAO_SCHEMA"."US_ACCIDENT_ADDRESS_DIM" as D on f.CITY=D.CITY and f.COUNTRY=D.COUNTRY and
f.STATE=D.STATE and f.ZIPCODE=D.ZIPCODE and f.COUNTY=D.COUNTY and f.TIMEZONE=D.TIMEZONE and f.AIRPORT_CODE=D.AIRPORT_CODE and
f.STREET=D.STREET group by D.ADD_ID
